# Generated by Django 4.2.24 on 2025-09-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlocation",
            name="radius_km",
            field=models.FloatField(default=0.5),
        ),
    ]
