# Generated by Django 4.2.24 on 2025-09-25 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount (KES)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "mpesa_receipt_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "checkout_request_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "merchant_request_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("result_code", models.CharField(blank=True, max_length=10, null=True)),
                ("result_desc", models.TextField(blank=True, null=True)),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
            ],
        ),
    ]
