# Generated by Django 5.2.6 on 2025-09-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_kes',
            new_name='amount',
        ),
    ]
