# Generated by Django 5.2.6 on 2025-09-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_status",
        ),
    ]
