# Generated by Django 4.2.24 on 2025-09-12 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("listing_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("edible", "Edible"), ("inedible", "Inedible")],
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("expiry_date", models.DateTimeField()),
                (
                    "discounted_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="listing_images/"
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("expired", "Expired")],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "upload_method",
                    models.CharField(
                        choices=[("manual", "Manual"), ("csv", "CSV")], max_length=10
                    ),
                ),
                ("pickup_window_duration", models.DateTimeField()),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
