# Generated by Django 5.2.6 on 2025-09-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('edible', 'Edible'), ('inedible', 'Inedible')], max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateTimeField()),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listing_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('expired', 'Expired')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_method', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV')], max_length=10)),
                ('pickup_window_duration', models.DateTimeField()),
            ],
        ),
    ]
