<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-12 14:43
=======
# Generated by Django 5.2.6 on 2025-09-12 15:14
>>>>>>> cb4752454e7d7c343db40964e5c1ded7f8a0a5c5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("inventory", "0001_initial"),
=======
        ('inventory', '0001_initial'),
>>>>>>> cb4752454e7d7c343db40964e5c1ded7f8a0a5c5
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="listing",
            name="producer",
            field=models.ForeignKey(
                limit_choices_to={"role": "producer"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
=======
            model_name='listing',
            name='producer',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'producer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
>>>>>>> cb4752454e7d7c343db40964e5c1ded7f8a0a5c5
        ),
    ]
