# Generated by Django 5.2.3 on 2025-09-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='producer',
        ),
    ]
