# Generated by Django 4.2.24 on 2025-11-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="pickup_point",
            field=models.CharField(
                blank=True,
                help_text="Specify the location where the item can be picked up",
                max_length=255,
                null=True,
            ),
        ),
    ]
