# Generated by Django 5.2.3 on 2025-09-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_listing_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
