# Generated by Django 5.2.3 on 2025-09-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_listing_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pickup_window_duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('expired', 'Expired')], default='available', max_length=20),
        ),
    ]
