# Generated by Django 4.2.24 on 2025-09-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_listing_pickup_window_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="pickup_window_duration",
            field=models.DateTimeField(),
        ),
    ]
