# Generated by Django 4.2.24 on 2025-09-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_listing_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="unit",
            field=models.CharField(
                choices=[("kg", "kg"), ("L", "L"), ("unit", "unit")],
                default=1,
                help_text="Select the unit: kg (weight), L (volume), or unit (count of items)",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
