# Generated by Django 5.2.6 on 2025-09-17 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_listing_producer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="unit",
            field=models.CharField(
                choices=[("kg", "kg"), ("L", "L"), ("unit", "unit")],
                default=1,
                help_text="Select the unit: kg (weight), L (volume), or unit (count of items)",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="producer",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"role": "producer"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
