# Generated by Django 4.2.24 on 2025-09-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_listing_unit"),
        ("inventory", "0007_listing_unit_alter_listing_producer"),
    ]

    operations = []
