# Generated by Django 5.2.6 on 2025-09-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('order_id', models.CharField(max_length=20)),
                ('ratings', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'reviews',
                'unique_together': {('user_id', 'order_id')},
            },
        ),
    ]
