# Generated by Django 5.2.6 on 2025-09-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
    ]
