# Generated by Django 4.2.24 on 2025-09-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="till_number",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
