# Generated by Django 5.2.6 on 2025-09-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
