# Generated by Django 5.2.6 on 2025-09-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
