# Generated by Django 4.2.24 on 2025-09-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_listing_pickup_window_duration"),
        ("orders", "0004_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.listing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wasteclaim",
            name="listing_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.listing",
            ),
            preserve_default=False,
        ),
    ]
