# Generated by Django 4.2.24 on 2025-09-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_orderitem_listing_wasteclaim_listing_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wasteclaim",
            old_name="listing_id",
            new_name="listing",
        ),
    ]
