# Generated by Django 4.2.24 on 2025-09-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_listing_pickup_window_duration"),
        ("orders", "0007_alter_orderitem_listing_alter_wasteclaim_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.listing",
            ),
        ),
        migrations.AlterField(
            model_name="wasteclaim",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.listing",
            ),
        ),
    ]
