# Generated by Django 4.2.24 on 2025-09-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_listing_pickup_window_duration"),
        ("orders", "0008_alter_orderitem_listing_alter_wasteclaim_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wasteclaim",
            name="pickup_window_end",
        ),
        migrations.AlterField(
            model_name="wasteclaim",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="inventory.listing",
            ),
        ),
    ]
