name: Django Deployment CI
on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: feedlink
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Django Migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/feedlink
        run: |
          python manage.py migrate
          # If you hit duplicate column later, uncomment below:
          # python manage.py migrate inventory 0005 --fake   # example

      - name: Collect Static Files (Optional)
        run: |
          python manage.py collectstatic --noinput

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Set up Git remote for Heroku
        run: |
          git remote add heroku https://git.heroku.com/feedlink-backend.git || echo "Heroku remote already exists"

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "feedlink"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}